ivr:
  menu:
    language: "nb_no"
    pause: 1
    default_queue: "annet"
    waitmusic: "http://s3.amazonaws.com/com.twilio.sounds.music/index.xml"
    menu_type: "spoken"
    options:
      - text: "Tast 1 for Salg!"
        value: 1
        options:
          - text: "Tast 1 for ny meny"
            value: 1
            options:
              - text: "Du har nådd testkøen, tast 1"
                queue: "test"
                value: 1
              - text: "Tast 9 for å bli satt over til Daglig leder!"
                value: 9
                dial:
                  - "+47XXXXXXXX"
          - text: "Tast 2 for en annen testkø"
            queue: "depot"
            value: 2
      - text: "Tast 2 for Kundeservice!"
        queue: "kundeservice"
        value: 2
      - text: "Tast 3 for andre henvendelser!"
        queue: "annet"
        value: 3
      - text: "Ring meg ved å taste 4"
        value: 4
