ivr:
  menu:
    language: "nb_no"
    pause: 1
    default_queue: "annet"
    waitmusic: ""
    menu_type: "played"
    options:
      - text: "Tast 1 for Salg!"
        route: "salg"
        value: 1
        options:
          - text: "Testing submenu"
            queue: "test"
            value: 1
      - text: "Tast 2 for Kundeservice!"
        queue: "kundeservice"
        value: 2
      - text: "Tast 3 for andre henvendelser!"
        queue: "annet"
        value: 3
