spring:
  profiles:
    active: menu,@activatedProperties@

management:
  metrics:
    enable:
      jvm: false
      logback: false
      tomcat: false
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health

twilio:
  account:
    sid: xxxxxxxxx
    api:
      secret: xxxxxxxxxx
